language: dart
sudo: false
dart:
  - dev

#script: ./tool/travis.sh

dart_task:
  - dartanalyzer: --fatal-infos --fatal-warnings example lib
  - dartfmt

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.pub-cache
